version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: l2top_app
    volumes:
      - ./src:/var/www
    networks:
      - appnet

  db:
    image: mysql:8.0
    container_name: l2top_db
    restart: always
    environment:
      MYSQL_DATABASE: l2top
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: l2top_user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - appnet

  nginx:
    image: nginx:latest
    container_name: l2top_nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  dbdata:
